Alik/feature/sharex data
Simple2B/ShareX.portal pull request #2
Opened 2021-07-15 13:53 UTC by tsyboom

2021-07-15 15:12 UTC, varvarashcherbyna7 approved these changes

2021-07-15 15:21 UTC, kipod requested changes

2021-07-15 15:21 UTC, kipod commented on app/models/content.py
> +    filename = fields.CharField(max_length=64)
max_length=260 (maximum file name length in windows)

2021-07-15 15:21 UTC, kipod commented on app/models/content.py
> +    content_type = fields.CharField(max_length=32)
max_length=64

2021-07-15 15:21 UTC, kipod commented on app/models/user.py
>      username = fields.CharField(max_length=32)
```max_length=64```
+
```python
email = fields.EMailField()
email_approved = fields.BooleanField()
```

2021-07-15 15:21 UTC, kipod commented on app/models/user.py
> +    api_key = fields.CharField(max_length=128)
default value?

2021-07-15 15:21 UTC, kipod commented on app/routers/auth.py
>  def get_user(user: User = Depends(get_current_user)):
Does only Admin have access to this route?
If yes - add that into TODO: comment line

2021-07-15 15:21 UTC, kipod commented on app/services/sharex.py
> +    filename = f"data/{str(uuid4())}"
better use absolute path (OK I know this is temp solution) Could you please add
```python
 # TODO: Store file on AWS S3
```

2021-07-15 15:21 UTC, kipod commented on app/services/auth.py
> +            api_key=str(uuid4()),
IMHO this field can be filled by default value in DB Model

2021-07-15 15:21 UTC, kipod commented on app/services/sharex.py
> +def exception(msg: str):
raise_error(

2021-07-15 15:21 UTC, kipod commented on tests/test_uploading_sharex.py
> +TEST_FILE = "/home/alik/simple2b/ShareX.portal/tests/test_data/Code_dPWe4YTTWI.png"
this path on YOUR MACHINE!!!

2021-07-15 15:21 UTC, kipod commented on tests/test_uploading_sharex.py
> +import pytest
pytest - is not standard module ----> import after typing

2021-07-15 15:21 UTC, kipod commented on tests/test_uploading_sharex.py
> +    assert content
need to add here validation if the content stored correct

2021-07-16 05:58 UTC, tsyboom commented on tests/test_uploading_sharex.py
> +    assert content
if data correct in record ?

2021-07-16 07:10 UTC, kipod approved these changes

2021-07-16 07:10 UTC, kipod commented on tests/test_uploading_sharex.py
> +    assert content
ну да :)

2021-07-16 07:10 UTC, merged